# -*- coding: utf-8 -*-
"""Trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZnS265mpdz3RpENhVrhHvRkQy-TOZ0t
"""

# Criação cardápio
produtos = {
    "001": {"nome": "Hamburguer    ", "preco": 10.0},
    "002": {"nome": "Refri Lata    ", "preco": 5.5},
    "003": {"nome": "Refri 1,5L    ", "preco": 9.0},
    "004": {"nome": "Refri 2,5L    ", "preco": 12.5},
    "005": {"nome": "Batata Frita  ", "preco": 8.0},
    "006": {"nome": "Sundae        ", "preco": 6.5},
    "007": {"nome": "Casquinha     ", "preco": 3.0},
    "008": {"nome": "Pizza P       ", "preco": 30.0},
    "009": {"nome": "Pizza M       ", "preco": 40.0},
    "010": {"nome": "Pizza G       ", "preco": 50.0}
}

# Inicialização variáveis e dicionários 
carrinho = {}
total = 0
valid = False

# Introdução
print('Seja bem-vindo ao nosso restaurante!')
print(' ')

# Começo do código
while True:
  # Instruções
  print('- Digite "Cardápio" para ver nossas opções.')
  print('- Digite "Carrinho" para abrir o carrinho de compras.')
  print('- Digite "Adicionar" para adicionar itens ao carrinho.')
  print('- Digite "Remover" para remover itens do carrinho.')
  print('- Digite "Fim" para finalizar pedido.')
  print('- Digite "Cancelar" para interromper qualquer operação de adição ou remoção.')
  print(' ')

  # Armazenando instrução
  esc = input('Escolha: ').lower().strip()
  print('--------------------------------------------------------------------------------')
  print(' ')

  # Printa cardápio
  if((esc == "cardápio") or (esc == "cardapio")):
    print('Itens do Cardápio:')
    print(' ')
    for item in produtos:
      print(f'{item}. {produtos[item]["nome"]} |   R${produtos[item]["preco"]}')
    print(' ')
    print(' ')
  
  # Mostrar carrinho
  elif(esc == "carrinho"):
    if(len(carrinho) == 0):
      print("O carrinho está vazio!")
    else:
      print("Código     Produto         Quantidade      Valor")
      print("--------------------------------------------------")
      for cod in carrinho:
        print(f' {cod}       {carrinho[cod]["Nome"]}      {carrinho[cod]["Quantidade"]}          R$ {carrinho[cod]["Subtotal"]:.2f}')
    
    print(' ')
    print(' ')
  
  # Adiciona item
  elif(esc == "adicionar"):
    while(valid == False):
      codigo = input("Digite o código do produto ou 'Cancelar' para voltar ao menu de operações: ").lower().strip()
      print(' ')

      if(codigo in produtos):
        print(f'{produtos[codigo]["nome"].strip()} foi selecionado.')
        quantidade = input("Digite a quantidade desejada: ").lower().strip()
        if quantidade == "cancelar":
          break
        nome_produto = produtos[codigo]["nome"]
        preco_unitario = produtos[codigo]["preco"]
        subtotal_item = preco_unitario * int(quantidade)

        if(codigo not in carrinho.keys()):
          carrinho[codigo] = {"Nome": nome_produto, "Quantidade": int(quantidade), "Subtotal": float(subtotal_item)}
        else:
          carrinho[codigo]["Quantidade"] += int(quantidade)
          carrinho[codigo]["Subtotal"] += subtotal_item
        
        print(' ')
        print(str(quantidade) + 'x ' + str(carrinho[codigo]['Nome']).strip() + ' foi adicionado no carrinho.')
        print(' ')

        valid = True
      elif codigo == "cancelar":
        break
      else:
        print("Código de produto inválido.")        
    print(' ')

    valid = False

  # Remover item
  elif(esc == "remover"):
    while(valid == False):
      if(len(carrinho) == 0):
        print("O carrinho está vazio! Adicione algo primeiro.")
        break
      codigo = input("Digite o código do produto ou 'Cancelar' para voltar ao menu de operações: ").lower().strip()
      print(' ')

      if(codigo in carrinho):
        print(f'{carrinho[codigo]["Quantidade"]}x {carrinho[codigo]["Nome"].strip()} foi selecionado.')
        quant = input("Digite a quantidade que deseja remover: ").lower().strip()
        print(' ')
        if quant == "cancelar":
          break
        carrinho[codigo]["Quantidade"] -= int(quant)
        carrinho[codigo]["Subtotal"] -= (int(quant) * produtos[codigo]["preco"])

        if(carrinho[codigo]["Quantidade"] <= 0):
          carrinho.pop(codigo)
          print('O produto foi removido.')
        valid = True
        print(' ')
        print(quant + 'x ' + str(carrinho[codigo]['Nome']).strip() + ' foi removido do carrinho.')
        print(' ')
      elif codigo.lower() == "cancelar":
        break
      else:
        print("Não há um produto com esse código no carrinho!")        
    print(' ')
    print(' ')

    valid = False

  # Finalizar pedido 
  elif(esc == "fim"):
    break
  else:
    print('Ação incorreta!')
    print('Digite novamente.')
    print(' ')
    print(' ')

# Print da notinha fiscal
print('                    Notinha                     ')
print(' ')
print("Código     Produto         Quantidade      Valor")
print("--------------------------------------------------")
for cod in carrinho:
  print(f' {cod}       {carrinho[cod]["Nome"]}      {carrinho[cod]["Quantidade"]}          R$ {carrinho[cod]["Subtotal"]:.2f}')
  total += carrinho[cod]["Subtotal"]

print("--------------------------------------------------")
print(f"Total                                     R$ {total:.2f}")



