# -*- coding: utf-8 -*-
"""Cópia de Trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yGzLAgiopoNP6jooaiwul7wbHCU9ZVOS
"""

# Criação cardápio
produtos = {
    "001": {"nome": "Hamburguer    ", "preco": 10.0},
    "002": {"nome": "Coca-Cola     ", "preco": 5.5},
    "003": {"nome": "Batata Frita  ", "preco": 8.0},
    "004": {"nome": "Sundae        ", "preco": 4.5}
}

# Inicialização variáveis e dicionários 
carrinho = {}
total = 0
valid = False

# Introdução
print('Seja bem-vindo ao nosso restaurante!')
print(' ')

# Começo do código
while True:
  # Instruções
  print('- Digite "Cardápio" para ver nossas opções.')
  print('- Digite "Carrinho" para abrir o carrinho de compras.')
  print('- Digite "Adicionar" para adicionar itens ao carrinho.')
  print('- Digite "Remover" para remover itens do carrinho.')
  print('- Digite "Fim" para finalizar pedido.')
  print(' ')

  # Armazenando instrução
  esc = input('Escolha: ')
  print(' ')
  print(' ')

  # Printa cardápio
  if((esc.lower() == "cardápio") or (esc.lower() == "cardapio")):
    print('Itens do Cardápio:')
    print(' ')
    for item in produtos:
      print(f'{item}. {produtos[item]["nome"]} |   R${produtos[item]["preco"]}')
    print(' ')
    print(' ')
  
  # Mostrar carrinho
  elif(esc.lower() == "carrinho"):
    if(len(carrinho) == 0):
      print("O carrinho está vazio!")
    else:
      print("Código     Produto         Quantidade      Valor")
      print("--------------------------------------------------")
      for cod in carrinho:
        print(f' {cod}       {carrinho[cod]["Nome"]}      {carrinho[cod]["Quantidade"]}          R$ {carrinho[cod]["Subtotal"]:.2f}')
    
    print(' ')
    print(' ')
  
  # Adiciona item
  elif(esc.lower() == "adicionar"):
    while(valid == False):
      codigo = input("Digite o código do produto: ")
      print(' ')

      if(codigo in produtos):
        quantidade = input("Digite a quantidade desejada: ")

        nome_produto = produtos[codigo]["nome"]
        preco_unitario = produtos[codigo]["preco"]
        subtotal_item = preco_unitario * int(quantidade)

        if(codigo not in carrinho.keys()):
          carrinho[codigo] = {"Nome": nome_produto, "Quantidade": int(quantidade), "Subtotal": float(subtotal_item)}
        else:
          carrinho[codigo]["Quantidade"] += int(quantidade)
          carrinho[codigo]["Subtotal"] += subtotal_item
        
        print(' ')
        print(str(quantidade) + 'x ' + str(carrinho[codigo]['Nome']).strip() + ' foi adicionado no carrinho.')
        print(' ')

        valid = True
      else:
        print("Código de produto inválido.")        
    print(' ')

    valid = False

  # Remover item
  elif(esc.lower() == "remover"):
    while(valid == False):
      codigo = input("Digite o código do produto: ")
      print(' ')

      if(codigo in carrinho):
        quant = input("Digite a quantidade: ")
        print(' ')
        print(' ')

        carrinho[codigo]["Quantidade"] -= int(quant)
        carrinho[codigo]["Subtotal"] -= (int(quant) * produtos[codigo]["preco"])

        if(carrinho[codigo]["Quantidade"] <= 0):
          carrinho.pop(codigo)
          print('O produto foi removido.')
        valid = True
        print(' ')
        print(quant + 'x ' + str(carrinho[codigo]['Nome']).strip() + ' foi removido do carrinho.')
        print(' ')
      else:
        print("Não há um produto com esse código no carrinho!")        
    print(' ')
    print(' ')

    valid = False

  # Finalizar pedido 
  elif(esc.lower() == "fim"):
    break
  else:
    print('Ação incorreta!')
    print('Digite novamente.')
    print(' ')
    print(' ')

# Print da notinha fiscal
print('                    Notinha                     ')
print(' ')
print("Código     Produto         Quantidade      Valor")
print("--------------------------------------------------")
for cod in carrinho:
  print(f' {cod}       {carrinho[cod]["Nome"]}      {carrinho[cod]["Quantidade"]}          R$ {carrinho[cod]["Subtotal"]:.2f}')
  total += carrinho[cod]["Subtotal"]

print("--------------------------------------------------")
print(f"Total                                     R$ {total:.2f}")

